### ISSUE TITLE
Xdelta3 creates broken files

### ISSUE THREAD

**Issue by btimofeev** [xperia64/android-rom-patcher#4]
Hello.
Sometimes your Xdelta3 patcher creates broken files. The checksum of the file is different from the checksum of patched file on computer.

**Comment by btimofeev** [comment]
You forgot to close the files after patching. Apparently this is the problem.

**Comment by xperia64** [comment]
Thank you. Fixed in 183925618eb3a0a8cccfea8cbad80c51a74aeaf6
